global:
  scrape_interval: 15s
  scrape_timeout: 10s

scrape_configs:

  # ExBuy Django/DRF 앱 메트릭 (4개 서버)
  - job_name: exbuy
    metrics_path: /metrics
    static_configs:
      - targets:
          - "exbuy-gunicorn-sync:8000"
          - "exbuy-gunicorn-gevent:8000"
          - "exbuy-gunicorn-gthread:8000"
          - "exbuy-uvicorn:8000"

  # cAdvisor 메트릭
  - job_name: cadvisor
    static_configs:
      - targets: ["cadvisor:8080"]

  - job_name: victoriametrics-self
    static_configs:
      - targets: ["victoriametrics:8428"]

  - job_name: vmagent-self
    static_configs:
      - targets: ["vmagent:8429"]

  - job_name: loki
    metrics_path: /metrics
    static_configs:
      - targets: ["loki:3100"]

  - job_name: promtail
    metrics_path: /metrics
    static_configs:
      - targets: ["promtail:9080"]
